# Generated by Django 3.0.5 on 2020-05-24 13:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_education_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='icon',
        ),
        migrations.AddField(
            model_name='skill',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
