# Generated by Django 3.0.5 on 2020-05-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20200524_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='content',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='url',
        ),
        migrations.AddField(
            model_name='skill',
            name='paradigm',
            field=models.CharField(choices=[('SE', 'Software Engineering'), ('WD', 'Web Development'), ('GM', 'Graphics and Media'), ('FW', 'Frameworks')], default='SE', max_length=2),
        ),
    ]
