# Generated by Django 3.0.5 on 2020-05-24 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20200524_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='paradigm',
        ),
    ]
