# Generated by Django 3.0.5 on 2020-05-24 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_remove_skill_paradigm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paradigm',
        ),
    ]
