# Generated by Django 3.0.5 on 2020-05-24 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_delete_paradigm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paradigm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=64)),
                ('paradigm', models.CharField(choices=[('SE', 'Software Engineering'), ('WD', 'Web Development'), ('GM', 'Graphics and Media'), ('FW', 'Frameworks')], max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='skill',
            name='paradigm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.Paradigm'),
        ),
    ]
